import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowUp,
  Battery,
  Bell,
  Camera,
  CameraOff,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cpu,
  Disc,
  Download,
  Droplet,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Globe,
  HelpCircle,
  Home,
  Info,
  Lock,
  LogOut,
  Mail,
  MessageCircle,
  Mic,
  Moon,
  Pencil,
  PlayCircle,
  Plus,
  PlusCircle,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Shield,
  Thermometer,
  Trash2,
  Truck,
  User,
  WifiOff,
  Wind,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react-native";
import React from "react";

const ICON_MAP: Record<string, LucideIcon> = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  battery: Battery,
  bell: Bell,
  camera: Camera,
  "camera-off": CameraOff,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clock: Clock,
  cpu: Cpu,
  disc: Disc,
  download: Download,
  droplet: Droplet,
  "edit-2": Pencil,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  filter: Filter,
  globe: Globe,
  "help-circle": HelpCircle,
  home: Home,
  info: Info,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  "message-circle": MessageCircle,
  mic: Mic,
  moon: Moon,
  pencil: Pencil,
  "play-circle": PlayCircle,
  plus: Plus,
  "plus-circle": PlusCircle,
  "rotate-ccw": RotateCcw,
  search: Search,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  thermometer: Thermometer,
  tool: Wrench,
  "trash-2": Trash2,
  truck: Truck,
  user: User,
  "wifi-off": WifiOff,
  wind: Wind,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

export type IconName = keyof typeof ICON_MAP;

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
}

export function Icon({ name, size = 24, color = "#000" }: IconProps) {
  const Component = ICON_MAP[name];
  if (!Component) return null;
  return <Component size={size} color={color} />;
}
